apiVersion: apps/v1
kind: Deployment
metadata:
  name: rommie-backend
  namespace: rommie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rommie-backend
  template:
    metadata:
      labels:
        app: rommie-backend
    spec:
      containers:
      - name: backend
        image: pratapad/rommie-backend:34569dccdaf8ca0e18030cce9cffb67a57c3b547
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://fullstackdbuser:Aditya%400007@fullstackcluster.h4kqmjc.mongodb.net/fullstackappdb"
        - name: JWT_SECRET
          value: "secret123"
        - name: PORT
          value: "5000"
        - name: CLOUDINARY_CLOUD_NAME
          value: "dfyire9xu"
        - name: CLOUDINARY_API_KEY
          value: "963362658922675"
        - name: CLOUDINARY_API_SECRET
          value: "oMa4u7E0RRI_LUZg9D_TDwf1WM8"
---
apiVersion: v1
kind: Service
metadata:
  name: rommie-backend-svc
  namespace: rommie
spec:
  selector:
    app: rommie-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP